### ISSUE TITLE
Locked in an angle

### ISSUE THREAD

**Issue by ravenfeld** [Jawnnypoo/PhysicsLayout#15]
My objects come to be blocked against the bounds of the layout
One idea to solve the problem?
Thank you.

**Comment by Jawnnypoo** [comment]
Sorry for the delay. Did you ever get this resolved?

**Comment by ravenfeld** [comment]
No, I think it comes from physics2D

**Comment by WajdiMuh** [comment]
i have the same problem

**Comment by WajdiMuh** [comment]
try to set the position iterations to 0

**Comment by Jawnnypoo** [comment]
If you are wanting the views to be able to "escape" the bounds of the layout, you can just set `app:bounds="false"` in XML
