### ISSUE TITLE
Consider making PixelsPerMeter a function of DP by default

### ISSUE THREAD

**Issue by mkonecny** [Jawnnypoo/PhysicsLayout#2]
Testing out this great library, and was a little puzzled when different DPI phones had boundaries at different positions. 

I've been able to set this myself using `setPixelsPerMeter` but I think it would be a great default if `50` was replaced by `50/3 * density` (since most phone densities today are 3 or 4)

**Comment by Jawnnypoo** [comment]
Good point here! This has been fixed on master. Appreciate the feedback! And be sure to check out the About section of the latest sample :+1:
