### ISSUE TITLE
Performance issue when I add more than 10 views

### ISSUE THREAD

**Issue by norman8154** [Jawnnypoo/PhysicsLayout#24]
Hi, 

I have encounter a performance issue when I built my own app.
That is when I add more than 10 object inside the view. It start getting lag and sometimes crashed.
I also download your sample app and everything seems fine.
So I make my code almost as same as yours. But the problem is still there.
Could you give my some advice or how you make your app's performance better?

**Comment by norman8154** [comment]
I figured it out. It's probably a problem with gradle version.

**Comment by Jawnnypoo** [comment]
Ah okay, thanks!
