### ISSUE TITLE
Applying force to views

### ISSUE THREAD

**Issue by pythoneer** [Jawnnypoo/PhysicsLayout#4]
Hi, i found your great Project and was amazed how quick this leads to cool looking results. After fiddling around a bit i was wondering how to apply a force to views. I want them to "fall" into the middle of the screen like there is the center of a huge mass. I'm trying to misuse the gravity property to simulate a force, but it would be nice to have an interface to the "bodys" of the box2d entitys.

Thanks for you work :)

**Comment by pythoneer** [comment]
Sry, i didn't really investigated your code. Clearly there is a simple way to do this

```
final Body viewBody1 = physicsRelativeLayout.getPhysics().findBodyById(R.id.view1);
viewBody1.applyForce(new Vec2(1000.4f, 1000.4f), new Vec2(0f, 0f));
```

sry for making the noise ;)

**Comment by Jawnnypoo** [comment]
You got it! I am glad you found that, not sure if many people have found/used that. I wish the call could be a bit shorter, but alas, the price you pay for allowing the physics to be applied to any custom view :)
