### ISSUE TITLE
Help with adding view to PhysicsLinearLayout

### ISSUE THREAD

**Issue by kexanie** [Jawnnypoo/PhysicsLayout#6]
Hi John, thank you for making this awesome library. I am trying to use it with my project. But when I tried to add child views to the `PhysicsLinearLayout`, the animation paused when new child view was added, like
```
physicsLayout = (ViewGroup) rootView.findViewById(R.id.physics_layout);
physicsLayout.addView(textView, params);
```
When a new `TextView` was added to the `PhysicalLinearLayout` meanwhile a previously added `TextView` was falling down, the latter will pause at the moment the new view was added. Any idea to solve this ?

Thanks again for this awesome library!

**Comment by Jawnnypoo** [comment]
So you are adding it at runtime? Hmm, yeah I will have to look into this. I don't think there is a fix you could do on your end, most likely something that will need to be fixed in the library :/. Glad you are enjoying the library otherwise!

**Comment by Jawnnypoo** [comment]
Good news, @kexanie this was fixed with commit d4916f1eed8a4f67bc149131687389100434a88e. Once I get another build out I will let you know and you can test with the latest and greatest.

**Comment by Jawnnypoo** [comment]
Release 1.0.1 is available now in jcenter if you would like to try and out and make sure this issue is resolved for you @kexanie

**Comment by kexanie** [comment]
Thanks for you response. Commit [`d4916f1`][1] fixed the bug of *rotation and volecity reset* when new view was added, which is helpful because I met the exactly same problem. But what I mentioned in this issue is actually another problem: the animation of previously added subview will pause, at the moment new subview was added, like this:

<img width="250" alt="device-2015-12-04-132357" src="https://cloud.githubusercontent.com/assets/5278523/11582703/d9e9e480-9a8c-11e5-9483-bd217327d842.png">

Sorry that my phone doesn't support video recording, otherwise a gif might better express what I mean. 

[1]:https://github.com/Jawnnypoo/PhysicsLayout/commit/d4916f1eed8a4f67bc149131687389100434a88e

**Comment by kexanie** [comment]
Great, the issue is resolved now. Thanks John.
